; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; Bibliothèques requises
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    esp32-camera

; Configuration du compilateur
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -O2
    -DCAMERA_MODEL_XIAO_ESP32S3

; Configuration de la mémoire
board_build.arduino.memory_type = opi_opi
board_build.arduino.psram_type = opi

; Partition scheme pour plus d'espace
board_build.partitions = huge_app.csv
